version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    container_name: go_app
    ports:
      - "8080:8080"
    environment:
      - ACT_MODE=${ACT_MODE}

  nginx:
    build:
      context: .
      target: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'

