version: "3.8"

services:
  nginx:
    build:
      context: .
      target: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt # Монтируем папку с сертификатами

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/log/letsencrypt:/var/log/letsencrypt
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'

  go_app:
    image: heilethan/yerd:0.0.15
    container_name: go_app
    ports:
      - "8081:8081"
    volumes:
      - ./main.db:/app/main.db
      - ./log.db:/app/log.db

  metric_app:
    image: heilethan/swadmin:0.0.3
    container_name: metric_app
    ports:
      - "3000:3000"
    volumes:
      - /home/erdanaerboluly/woerter/main.db:/app/main.db
