version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    container_name: go_app
    ports:
      - "8080:8080"
    environment:
      - ACT_MODE=prod

  nginx:
    build:
      context: .
      target: nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
