import { LanguageText } from "./all_text";

export const ZH_TEXT: LanguageText = {
  value: "chinese",
  t: {
    WORD: {
      CREATE: "添加",
      SHOW_FULL: "显示全部",
      EMPTY1: "这里是空的，",
      EMPTY2: "添加新单词 🤪",
    },
    PLAY: {
      H1_P1: "让我们",
      H1_P2: "学习！",
      MAX: "复习单词数（最多50个）",
      GO: "开始吧！",
    },
    ONBOARD: {
      THIS_H1: "选择您的主要语言：",
      THIS_P1: `选择您流利使用的语言。所有界面和单词描述都将使用此语言。您每30天只能更改一次语言。`,
      THIS_B1: "保存",
      ANOTHER_H1: "选择要学习的语言：",
      ANOTHER_P1: "仅选择您真正想学习的语言。",
      ANOTHER_P2: "您还没有选择任何语言。",
      ANOTHER_P3: "您已选择：",
      ANOTHER_B1: "保存",
    },
    ASK: {
      B1: "生成",
      B2: "前往单词",
      SELF: "我自己写",
      YOUR_LANG: "用 ",
      INPUT_P: "保持简短清晰 ;)",
      G_M: "如何获得好结果？",
      G1: "- 用以下语言写单词：",
      G2: "- 写单词时不做语法变化",
      G3: "- 如果可能，只写单词或短语",
    },
    LOGIN: {
      WELCOME: "欢迎！",
      NEXT: "请使用 Google 登录继续 👀",
      GOOGLE: "使用 Google 登录",
    },
    CREATE: {
      P_EN: `用英语解释单词 "[[]]" 的意思。答案需要用英语写。首先，解释这个词的基本意思。然后用英语造3个句子并提供翻译。具体解释每个句子的上下文中的单词含义。写得简明扼要，不要有不必要的信息。答案需要没有 Markdown 格式。`,
      P_DE: `用英语解释单词 "[[]]" 的意思。答案需要用英语写。首先，解释这个词的基本意思。然后用德语造3个句子并提供翻译。具体解释每个句子的上下文中的单词含义。写得简明扼要，不要有不必要的信息。答案需要没有 Markdown 格式。`,
      TITLE: "您的单词：",
      TITLE_P: "保持简短清晰 ;)",
      DESC: "这是什么意思：",
      DESC_P: "为您的单词写一个描述：",
      SELF: "我想自己做",
      GEN: "生成",
      GEN1: "1. 复制提示：",
      GEN2_P1: "2. 访问网站 ",
      GEN2_P2: " 并粘贴文本",
      GEN3: "3. 复制结果并粘贴到描述字段",
      SAVE: "保存",
    },
    EDIT: {
      TITLE: "您的单词：",
      TITLE_P: "保持简短清晰 ;)",
      DESC: "这是什么意思：",
      DESC_P: "为您的单词写一个描述：",
      DELETE: "删除",
      SAVE: "保存",
    },
    GOPLAY: {
      END: "结束",
      NEXT: "下一步",
      BACK: "返回",
    },
    HEADER: {
      WORDS: "单词",
      PLAY: "游戏",
      PROFILE: "个人资料",
      HI: "你好，",
      NEW: "新单词",
      CHOOSE: "选择语言",
    },
    PROFILE: {
      TLANGS: "您正在学习这些语言：",
      OSLANG: "系统语言：",
      LOGOUT: "登出",
    },
  },
};
